// game/config/gameSetupConfig.js

const PLAYERS = {
  TWO_PLAYERS: "2P",
  THREE_PLAYERS: "3P",
  FOUR_PLAYERS: "4P",
};

const CHIPS_QUANTITY = {
  [PLAYERS.TWO_PLAYERS]: {
    chipQuantity: 4,
  },
  [PLAYERS.THREE_PLAYERS]: {
    chipQuantity: 5,
  },
  [PLAYERS.FOUR_PLAYERS]: {
    chipQuantity: 7,
  },
};

const NOBLE_TILES_QUNTITY = {
  [PLAYERS.TWO_PLAYERS]: {
    nobleTiles: 3,
  },
  [PLAYERS.THREE_PLAYERS]: {
    nobleTiles: 4,
  },
  [PLAYERS.FOUR_PLAYERS]: {
    nobleTiles: 5,
  },
};

const DEV_CARDS = {
  ["LEVEL_ONE"]: [
    // Black
    {
      color: "black",
      cost: { red: 1, green: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1b1",
    },
    {
      color: "black",
      cost: { green: 3 },
      prestigePoints: 0,
      level: 1,
      index: "1b2",
    },
    {
      color: "black",
      cost: { white: 1, blue: 1, red: 1, green: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1b3",
    },
    {
      color: "black",
      cost: { white: 2, green: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1b4",
    },
    {
      color: "black",
      cost: { blue: 4 },
      prestigePoints: 1,
      level: 1,
      index: "1b5",
    },
    {
      color: "black",
      cost: { white: 1, blue: 2, red: 1, green: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1b6",
    },
    {
      color: "black",
      cost: { white: 2, blue: 2, red: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1b7",
    },
    {
      color: "black",
      cost: { red: 3, green: 1, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1b8",
    },
    // Blue
    {
      color: "blue",
      cost: { white: 1, black: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1l1",
    },

    {
      color: "blue",
      cost: { black: 3 },
      prestigePoints: 0,
      level: 1,
      index: "1l2",
    },
    {
      color: "blue",
      cost: { white: 1, red: 1, green: 1, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1l3",
    },

    {
      color: "blue",
      cost: { green: 2, black: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1l4",
    },
    {
      color: "blue",
      cost: { red: 4 },
      prestigePoints: 1,
      level: 1,
      index: "1l5",
    },
    {
      color: "blue",
      cost: { white: 1, red: 2, green: 1, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1l6",
    },
    {
      color: "blue",
      cost: { white: 1, red: 2, green: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1l7",
    },
    {
      color: "blue",
      cost: { blue: 1, red: 1, green: 3 },
      prestigePoints: 0,
      level: 1,
      index: "1l8",
    },
    // Green
    {
      color: "green",
      cost: { white: 2, blue: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1g1",
    },
    {
      color: "green",
      cost: { red: 3 },
      prestigePoints: 0,
      level: 1,
      index: "1g2",
    },
    {
      color: "green",
      cost: { white: 1, blue: 1, red: 1, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1g3",
    },
    {
      color: "green",
      cost: { blue: 2, red: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1g4",
    },
    {
      color: "green",
      cost: { black: 4 },
      prestigePoints: 1,
      level: 1,
      index: "1g5",
    },
    {
      color: "green",
      cost: { white: 1, blue: 1, red: 1, black: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1g6",
    },
    {
      color: "green",
      cost: { blue: 1, red: 2, black: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1g7",
    },
    {
      color: "green",
      cost: { white: 1, blue: 3, green: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1g8",
    },
    // Red
    {
      color: "red",
      cost: { blue: 2, green: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1r1",
    },
    {
      color: "red",
      cost: { white: 3 },
      prestigePoints: 0,
      level: 1,
      index: "1r2",
    },
    {
      color: "red",
      cost: { white: 1, blue: 1, green: 1, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1r3",
    },
    {
      color: "red",
      cost: { white: 2, red: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1r4",
    },
    {
      color: "red",
      cost: { white: 4 },
      prestigePoints: 1,
      level: 1,
      index: "1r5",
    },
    {
      color: "red",
      cost: { white: 2, blue: 1, green: 1, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1r6",
    },
    {
      color: "red",
      cost: { white: 2, green: 1, black: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1r7",
    },
    {
      color: "red",
      cost: { white: 1, red: 1, black: 3 },
      prestigePoints: 0,
      level: 1,
      index: "1r8",
    },
    // White
    {
      color: "white",
      cost: { blue: 3 },
      prestigePoints: 0,
      level: 1,
      index: "1w1",
    },
    {
      color: "white",
      cost: { red: 2, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1w2",
    },
    {
      color: "white",
      cost: { blue: 1, red: 1, green: 1, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1w3",
    },
    {
      color: "white",
      cost: { blue: 2, black: 2 },
      prestigePoints: 0,
      level: 1,
      index: "1w4",
    },
    {
      color: "white",
      cost: { green: 4 },
      prestigePoints: 1,
      level: 1,
      index: "1w5",
    },
    {
      color: "white",
      cost: { blue: 1, red: 1, green: 2, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1w6",
    },
    {
      color: "white",
      cost: { blue: 2, green: 2, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1w7",
    },
    {
      color: "white",
      cost: { white: 3, blue: 1, black: 1 },
      prestigePoints: 0,
      level: 1,
      index: "1w8",
    },
  ],
  ["LEVEL_TWO"]: [
    // Black
    {
      color: "black",
      cost: { white: 5 },
      prestigePoints: 2,
      level: 2,
      index: "2b1",
    },
    {
      color: "black",
      cost: { black: 6 },
      prestigePoints: 3,
      level: 2,
      index: "2b2",
    },
    {
      color: "black",
      cost: { white: 3, blue: 2, green: 2 },
      prestigePoints: 1,
      level: 2,
      index: "2b3",
    },
    {
      color: "black",
      cost: { blue: 1, red: 2, green: 4 },
      prestigePoints: 2,
      level: 2,
      index: "2b4",
    },
    {
      color: "black",
      cost: { white: 3, green: 3, black: 2 },
      prestigePoints: 1,
      level: 2,
      index: "2b5",
    },
    {
      color: "black",
      cost: { red: 3, green: 5 },
      prestigePoints: 2,
      level: 2,
      index: "2b6",
    },
    // Blue
    {
      color: "blue",
      cost: { blue: 5 },
      prestigePoints: 2,
      level: 2,
      index: "2l1",
    },
    {
      color: "blue",
      cost: { blue: 6 },
      prestigePoints: 3,
      level: 2,
      index: "2l2",
    },
    {
      color: "blue",
      cost: { blue: 2, red: 3, green: 2 },
      prestigePoints: 1,
      level: 2,
      index: "2l3",
    },
    {
      color: "blue",
      cost: { white: 2, red: 1, black: 4 },
      prestigePoints: 2,
      level: 2,
      index: "2l4",
    },
    {
      color: "blue",
      cost: { blue: 2, green: 3, black: 3 },
      prestigePoints: 1,
      level: 2,
      index: "2l5",
    },
    {
      color: "blue",
      cost: { white: 5, blue: 3 },
      prestigePoints: 2,
      level: 2,
      index: "2l6",
    },
    // Green
    {
      color: "green",
      cost: { green: 5 },
      prestigePoints: 2,
      level: 2,
      index: "2g1",
    },
    {
      color: "green",
      cost: { green: 6 },
      prestigePoints: 3,
      level: 2,
      index: "2g2",
    },
    {
      color: "green",
      cost: { white: 2, blue: 3, black: 2 },
      prestigePoints: 1,
      level: 2,
      index: "2g3",
    },
    {
      color: "green",
      cost: { white: 4, blue: 2, black: 1 },
      prestigePoints: 2,
      level: 2,
      index: "2g4",
    },
    {
      color: "green",
      cost: { white: 3, red: 3, green: 2 },
      prestigePoints: 1,
      level: 2,
      index: "2g5",
    },
    {
      color: "green",
      cost: { blue: 5, green: 3 },
      prestigePoints: 2,
      level: 2,
      index: "2g6",
    },
    // Red
    {
      color: "red",
      cost: { black: 5 },
      prestigePoints: 2,
      level: 2,
      index: "2r1",
    },
    {
      color: "red",
      cost: { red: 6 },
      prestigePoints: 3,
      level: 2,
      index: "2r2",
    },
    {
      color: "red",
      cost: { white: 2, red: 2, black: 3 },
      prestigePoints: 1,
      level: 2,
      index: "2r3",
    },
    {
      color: "red",
      cost: { white: 1, blue: 4, green: 2 },
      prestigePoints: 2,
      level: 2,
      index: "2r4",
    },
    {
      color: "red",
      cost: { blue: 3, red: 2, black: 3 },
      prestigePoints: 1,
      level: 2,
      index: "2r5",
    },
    {
      color: "red",
      cost: { white: 3, black: 5 },
      prestigePoints: 2,
      level: 2,
      index: "2r6",
    },
    // White
    {
      color: "white",
      cost: { red: 5 },
      prestigePoints: 2,
      level: 2,
      index: "2w1",
    },
    {
      color: "white",
      cost: { white: 6 },
      prestigePoints: 3,
      level: 2,
      index: "2w2",
    },
    {
      color: "white",
      cost: { red: 2, green: 3, black: 2 },
      prestigePoints: 1,
      level: 2,
      index: "2w3",
    },
    {
      color: "white",
      cost: { red: 4, green: 1, black: 2 },
      prestigePoints: 2,
      level: 2,
      index: "2w4",
    },
    {
      color: "white",
      cost: { white: 2, blue: 3, red: 3 },
      prestigePoints: 1,
      level: 2,
      index: "2w5",
    },
    {
      color: "white",
      cost: { red: 5, black: 3 },
      prestigePoints: 2,
      level: 2,
      index: "2w6",
    },
  ],
  ["LEVEL_THREE"]: [
    // Black
    {
      color: "black",
      cost: { red: 7 },
      prestigePoints: 4,
      level: 3,
      index: "3b1",
    },
    {
      color: "black",
      cost: { red: 7, black: 3 },
      prestigePoints: 5,
      level: 3,
      index: "3b2",
    },
    {
      color: "black",
      cost: { red: 6, green: 3, black: 3 },
      prestigePoints: 4,
      level: 3,
      index: "3b3",
    },
    {
      color: "black",
      cost: { white: 3, blue: 3, red: 3, green: 5 },
      prestigePoints: 3,
      level: 3,
      index: "3b4",
    },
    // Blue
    {
      color: "blue",
      cost: { white: 7 },
      prestigePoints: 4,
      level: 3,
      index: "3l1",
    },
    {
      color: "blue",
      cost: { white: 7, blue: 3 },
      prestigePoints: 5,
      level: 3,
      index: "3l2",
    },
    {
      color: "blue",
      cost: { white: 6, blue: 3, black: 3 },
      prestigePoints: 4,
      level: 3,
      index: "3l3",
    },
    {
      color: "blue",
      cost: { white: 3, red: 3, green: 3, black: 5 },
      prestigePoints: 3,
      level: 3,
      index: "3l4",
    },
    // Green
    {
      color: "green",
      cost: { blue: 7 },
      prestigePoints: 4,
      level: 3,
      index: "3g1",
    },
    {
      color: "green",
      cost: { blue: 7, green: 3 },
      prestigePoints: 5,
      level: 3,
      index: "3g2",
    },
    {
      color: "green",
      cost: { white: 3, blue: 6, green: 3 },
      prestigePoints: 4,
      level: 3,
      index: "3g3",
    },
    {
      color: "green",
      cost: { white: 5, blue: 3, red: 3, black: 3 },
      prestigePoints: 3,
      level: 3,
      index: "3g4",
    },
    // Red
    {
      color: "red",
      cost: { green: 7 },
      prestigePoints: 4,
      level: 3,
      index: "3r1",
    },
    {
      color: "red",
      cost: { red: 3, green: 7 },
      prestigePoints: 5,
      level: 3,
      index: "3r2",
    },
    {
      color: "red",
      cost: { blue: 3, red: 3, green: 6 },
      prestigePoints: 4,
      level: 3,
      index: "3r3",
    },
    {
      color: "red",
      cost: { white: 3, blue: 5, green: 3, black: 3 },
      prestigePoints: 3,
      level: 3,
      index: "3r4",
    },
    // White
    {
      color: "white",
      cost: { black: 7 },
      prestigePoints: 4,
      level: 3,
      index: "3w1",
    },
    {
      color: "white",
      cost: { white: 3, black: 7 },
      prestigePoints: 5,
      level: 3,
      index: "3w2",
    },
    {
      color: "white",
      cost: { white: 3, red: 3, black: 6 },
      prestigePoints: 4,
      level: 3,
      index: "3w3",
    },
    {
      color: "white",
      cost: { blue: 3, red: 5, green: 3, black: 3 },
      prestigePoints: 3,
      level: 3,
      index: "3w4",
    },
  ],
};

const NOBLE_TILES = [
  {
    cost: { white: 3, blue: 3, black: 3 },
    prestigePoints: 3,
    index: "1",
  },
  {
    cost: { blue: 3, red: 3, green: 3 },
    prestigePoints: 3,
    index: "2",
  },
  {
    cost: { white: 3, red: 3, black: 3 },
    prestigePoints: 3,
    index: "3",
  },

  {
    cost: { white: 3, blue: 3, green: 3 },
    prestigePoints: 3,
    index: "4",
  },
  {
    cost: { red: 3, green: 3, black: 3 },
    prestigePoints: 3,
    index: "5",
  },
  {
    cost: { red: 4, green: 4 },
    prestigePoints: 3,
    index: "6",
  },
  {
    cost: { blue: 4, green: 4 },
    prestigePoints: 3,
    index: "7",
  },
  {
    cost: { red: 4, black: 4 },
    prestigePoints: 3,
    index: "8",
  },
  {
    cost: { white: 4, black: 4 },
    prestigePoints: 3,
    index: "9",
  },
  {
    cost: { white: 4, blue: 4 },
    prestigePoints: 3,
    index: "10",
  },
];

module.exports = {
  PLAYERS,
  DEV_CARDS,
  CHIPS_QUANTITY,
  NOBLE_TILES_QUNTITY,
  NOBLE_TILES,
};
