// game/config/journeyMapNodes.js
const JOURNEY_TYPES = {
  QUICK: "quick",
  LONG: "long",
};

const journeyMapNodes = {
  [JOURNEY_TYPES.QUICK]: {
    0: {
      id: 0,
      name: "Start",
      isEnd: false,
      // effect: null,
      // effect: "flogging",
      effect: "cabin_search",
      // effect: "off_with_tongue",
      // effect: "feed_the_kraken",
      next: {
        blue: 1,
        yellow: 2,
        red: 3,
      },
    },
    1: {
      id: 1,
      name: "",
      isEnd: false,
      // effect: null,
      effect: "cabin_search",
      // effect: "off_with_tongue",
      // effect: "feed_the_kraken",
      // effect: "flogging",
      next: {
        blue: 4,
        yellow: 5,
        red: 2,
      },
    },
    2: {
      id: 2,
      name: "",
      isEnd: false,
      // effect: null,
      // effect: "feed_the_kraken",
      // effect: "cabin_search",
      effect: "off_with_tongue",
      // effect: "flogging",
      next: {
        blue: 5,
        yellow: 7,
        red: 7,
      },
    },
    3: {
      id: 3,
      name: "",
      isEnd: false,
      // effect: null,
      // effect: "off_with_tongue",
      // effect: "cabin_search",
      // effect: "feed_the_kraken",
      effect: "flogging",
      next: {
        blue: 2,
        yellow: 7,
        red: 8,
      },
    },
    4: {
      id: 4,
      name: "",
      isEnd: false,
      // effect: null,
      effect: "off_with_tongue",
      // effect: "feed_the_kraken",
      // effect: "cabin_search",
      next: {
        blue: 9,
        yellow: 9,
        red: 5,
      },
    },
    5: {
      id: 5,
      name: "",
      isEnd: false,
      // effect: "cabin_search",
      effect: "off_with_tongue",
      // effect: "feed_the_kraken",
      next: {
        blue: 9,
        yellow: 10,
        red: 6,
      },
    },
    6: {
      id: 6,
      name: "",
      isEnd: false,
      // effect: null,
      // effect: "off_with_tongue",
      effect: "feed_the_kraken",
      // effect: "cabin_search",
      next: {
        blue: 10,
        yellow: 11,
        red: 12,
      },
    },
    7: {
      id: 7,
      name: "",
      isEnd: false,
      // effect: "cabin_search",
      effect: "off_with_tongue",
      // effect: "feed_the_kraken",
      next: {
        blue: 6,
        yellow: 12,
        red: 13,
      },
    },
    8: {
      id: 8,
      name: "",
      isEnd: false,
      // effect: null,
      effect: "feed_the_kraken",
      // effect: "off_with_tongue",
      // effect: "cabin_search",
      next: {
        blue: 7,
        yellow: 13,
        red: 13,
      },
    },
    9: {
      id: 9,
      name: "",
      isEnd: false,
      // effect: null,
      effect: "off_with_tongue",
      // effect: "cabin_search",
      next: {
        blue: 14,
        yellow: 15,
        red: 10,
      },
    },
    10: {
      id: 10,
      name: "",
      isEnd: false,
      // effect: null,
      effect: "off_with_tongue",
      // effect: "cabin_search",
      next: {
        blue: 15,
        yellow: 16,
        red: 11,
      },
    },
    11: {
      id: 11,
      name: "",
      isEnd: false,
      // effect: null,
      effect: "cabin_search",
      // effect: "off_with_tongue",
      next: {
        blue: 16,
        yellow: 17,
        red: 18,
      },
    },
    12: {
      id: 12,
      name: "",
      isEnd: false,
      // effect: null,
      effect: "cabin_search",
      // effect: "off_with_tongue",
      next: {
        blue: 11,
        yellow: 18,
        red: 19,
      },
    },
    13: {
      id: 13,
      name: "",
      isEnd: false,
      effect: "cabin_search",
      next: {
        blue: 12,
        yellow: 19,
        red: 20,
      },
    },
    14: {
      id: 14,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 21,
        yellow: 15,
        red: 15,
      },
    },
    15: {
      id: 15,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 21,
        yellow: 16,
        red: 16,
      },
    },
    16: {
      id: 16,
      name: "",
      isEnd: false,
      effect: "feed_the_kraken",
      next: {
        blue: 21,
        yellow: 21,
        red: 17,
      },
    },
    17: {
      id: 17,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 21,
        yellow: 22,
        red: 23,
      },
    },
    18: {
      id: 18,
      name: "",
      isEnd: false,
      effect: "feed_the_kraken",
      next: {
        blue: 17,
        yellow: 23,
        red: 23,
      },
    },
    19: {
      id: 19,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 18,
        yellow: 18,
        red: 23,
      },
    },
    20: {
      id: 20,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 19,
        yellow: 19,
        red: 23,
      },
    },
    21: {
      id: 21,
      name: "",
      isEnd: true,
      effect: null,
      winner: "sailors",
      next: {},
    },
    22: {
      id: 22,
      name: "",
      isEnd: true,
      winner: "cult",
      effect: null,
      next: {},
    },
    23: {
      id: 23,
      name: "",
      isEnd: true,
      winner: "pirates",
      effect: null,
      next: {},
    },
  },

  [JOURNEY_TYPES.LONG]: {
    0: {
      id: 0,
      name: "Start",
      isEnd: false,
      effect: null,
      next: {
        blue: 1,
        yellow: 2,
        red: 3,
      },
    },

    1: {
      id: 1,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 4,
        yellow: 4,
        red: 2,
      },
    },

    2: {
      id: 2,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 4,
        yellow: 5,
        red: 6,
      },
    },

    3: {
      id: 3,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 2,
        yellow: 6,
        red: 6,
      },
    },
    4: {
      id: 4,
      name: "",
      isEnd: false,
      effect: "cabin_search",
      next: {
        blue: 7,
        yellow: 8,
        red: 5,
      },
    },
    5: {
      id: 5,
      name: "",
      isEnd: false,
      effect: "cabin_search",
      next: {
        blue: 8,
        yellow: 10,
        red: 10,
      },
    },
    6: {
      id: 6,
      name: "",
      isEnd: false,
      effect: "cabin_search",
      next: {
        blue: 5,
        yellow: 10,
        red: 11,
      },
    },
    7: {
      id: 7,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 12,
        yellow: 12,
        red: 8,
      },
    },
    8: {
      id: 8,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 12,
        yellow: 13,
        red: 9,
      },
    },
    9: {
      id: 9,
      name: "",
      isEnd: false,
      effect: "off_with_tongue",
      next: {
        blue: 13,
        yellow: 14,
        red: 15,
      },
    },
    10: {
      id: 10,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 9,
        yellow: 15,
        red: 16,
      },
    },
    11: {
      id: 11,
      name: "",
      isEnd: false,
      effect: "cabin_search",
      next: {
        blue: 10,
        yellow: 16,
        red: 16,
      },
    },
    12: {
      id: 12,
      name: "",
      isEnd: false,
      effect: null,
      gunReload: true,
      next: {
        blue: 17,
        yellow: 18,
        red: 13,
      },
    },
    13: {
      id: 13,
      name: "",
      isEnd: false,
      effect: "flogging",
      gunReload: true,
      next: {
        blue: 18,
        yellow: 19,
        red: 14,
      },
    },
    14: {
      id: 14,
      name: "",
      isEnd: false,
      effect: null,
      gunReload: true,
      next: {
        blue: 19,
        yellow: 20,
        red: 21,
      },
    },
    15: {
      id: 15,
      name: "",
      isEnd: false,
      effect: "flogging",
      gunReload: true,
      next: {
        blue: 14,
        yellow: 21,
        red: 22,
      },
    },
    16: {
      id: 16,
      name: "",
      isEnd: false,
      effect: null,
      gunReload: true,
      next: {
        blue: 15,
        yellow: 22,
        red: 23,
      },
    },
    17: {
      id: 17,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 24,
        yellow: 18,
        red: 18,
      },
    },
    18: {
      id: 18,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 24,
        yellow: 19,
        red: 19,
      },
    },
    19: {
      id: 19,
      name: "",
      isEnd: false,
      effect: "feed_the_kraken",
      next: {
        blue: 24,
        yellow: 24,
        red: 20,
      },
    },
    20: {
      id: 20,
      name: "",
      isEnd: false,
      effect: "feed_the_kraken",
      next: {
        blue: 24,
        yellow: 25,
        red: 26,
      },
    },
    21: {
      id: 21,
      name: "",
      isEnd: false,
      effect: "feed_the_kraken",
      next: {
        blue: 20,
        yellow: 26,
        red: 26,
      },
    },
    22: {
      id: 22,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 21,
        yellow: 21,
        red: 26,
      },
    },
    23: {
      id: 23,
      name: "",
      isEnd: false,
      effect: null,
      next: {
        blue: 22,
        yellow: 22,
        red: 26,
      },
    },
    24: {
      id: 24,
      name: "",
      isEnd: true,
      effect: null,
      winner: "sailors",
      next: {},
    },
    25: {
      id: 25,
      name: "",
      isEnd: true,
      winner: "cult",
      effect: null,
      next: {},
    },
    26: {
      id: 26,
      name: "",
      isEnd: true,
      winner: "pirates",
      effect: null,
      next: {},
    },
  },
};

module.exports = {
  JOURNEY_TYPES,
  journeyMapNodes,
};
