// game/config/gameSetupConfig.js

const DEV_CARDS = {
  ["LEVEL_ONE"]: [
    // Black
    {
      color: "black",
      cost: { red: 1, green: 1, blue: 1, white: 1 },
      prestigePoints: 0,
      crowns: 0,
      level: 1,
      index: "1b1",
    },
    {
      color: "black",
      cost: { pearl: 1, blue: 2, white: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "turn",
      level: 1,
      index: "1b2",
    },
    {
      color: "black",
      cost: { red: 2, green: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "take-second-same",
      level: 1,
      index: "1b3",
    },
    {
      color: "black",
      cost: { green: 3, blue: 2 },
      prestigePoints: 1,
      crowns: 0,
      level: 1,
      index: "1b4",
    },
    {
      color: "black",
      cost: { white: 3 },
      prestigePoints: 0,
      crowns: 1,
      level: 1,
      index: "1b5",
    },
    // Blue
    {
      color: "blue",
      cost: { black: 1, red: 1, green: 1, white: 1 },
      prestigePoints: 0,
      crowns: 0,
      level: 1,
      index: "1l1",
    },

    {
      color: "blue",
      cost: { pearl: 1, red: 2, green: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "turn",
      level: 1,
      index: "1l2",
    },
    {
      color: "blue",
      cost: { black: 2, white: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "take-second-same",
      level: 1,
      index: "1l3",
    },

    {
      color: "blue",
      cost: { black: 3, red: 2 },
      prestigePoints: 1,
      crowns: 0,
      level: 1,
      index: "1l4",
    },
    {
      color: "blue",
      cost: { green: 3 },
      prestigePoints: 0,
      crowns: 1,
      level: 1,
      index: "1l5",
    },

    // Green
    {
      color: "green",
      cost: { black: 1, red: 1, blue: 1, white: 1 },
      prestigePoints: 0,
      crowns: 0,
      level: 1,
      index: "1g1",
    },
    {
      color: "green",
      cost: { pearl: 1, black: 2, red: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "turn",
      level: 1,
      index: "1g2",
    },
    {
      color: "green",
      cost: { blue: 2, white: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "take-second-same",
      level: 1,
      index: "1g3",
    },
    {
      color: "green",
      cost: { black: 2, white: 3 },
      prestigePoints: 1,
      crowns: 0,
      level: 1,
      index: "1g4",
    },
    {
      color: "green",
      cost: { red: 3 },
      prestigePoints: 0,
      crowns: 1,
      level: 1,
      index: "1g5",
    },
    // Red
    {
      color: "red",
      cost: { black: 1, green: 1, blue: 1, white: 1 },
      prestigePoints: 0,
      crowns: 0,
      level: 1,
      index: "1r1",
    },
    {
      color: "red",
      cost: { pearl: 1, black: 2, white: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "turn",
      level: 1,
      index: "1r2",
    },
    {
      color: "red",
      cost: { green: 2, blue: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "take-second-same",
      level: 1,
      index: "1r3",
    },
    {
      color: "red",
      cost: { blue: 3, white: 2 },
      prestigePoints: 1,
      crowns: 0,
      level: 1,
      index: "1r4",
    },
    {
      color: "red",
      cost: { black: 3 },
      prestigePoints: 0,
      crowns: 1,
      level: 1,
      index: "1r5",
    },
    // White
    {
      color: "white",
      cost: { black: 1, red: 1, green: 1, blue: 1 },
      prestigePoints: 0,
      crowns: 0,
      level: 1,
      index: "1w1",
    },
    {
      color: "white",
      cost: { pearl: 1, green: 2, blue: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "turn",
      level: 1,
      index: "1w2",
    },
    {
      color: "white",
      cost: { black: 2, red: 2 },
      prestigePoints: 0,
      crowns: 0,
      ability: "take-second-same",
      level: 1,
      index: "1w3",
    },
    {
      color: "white",
      cost: { red: 3, green: 2 },
      prestigePoints: 1,
      crowns: 0,
      level: 1,
      index: "1w4",
    },
    {
      color: "white",
      cost: { blue: 3 },
      prestigePoints: 0,
      crowns: 1,
      level: 1,
      index: "1w5",
    },
    {
      color: "points",
      cost: { pearl: 1, red: 4 },
      prestigePoints: 3,
      crowns: 0,
      level: 1,
      index: "1p",
    },
    {
      color: "joker",
      cost: { pearl: 1, black: 4 },
      prestigePoints: 1,
      crowns: 0,
      level: 1,
      index: "1j1",
    },
    {
      color: "joker",
      cost: { pearl: 1, white: 4 },
      prestigePoints: 0,
      crowns: 1,
      level: 1,
      index: "1j2",
    },
    {
      color: "joker",
      cost: { pearl: 1, black: 1, green: 2, white: 2 },
      prestigePoints: 1,
      crowns: 0,
      level: 1,
      index: "1j3",
    },
    {
      color: "joker",
      cost: { pearl: 1, black: 1, red: 2, blue: 2 },
      prestigePoints: 1,
      crowns: 0,
      level: 1,
      index: "1j4",
    },
  ],
  ["LEVEL_TWO"]: [
    // Black
    {
      color: "black",
      cost: { green: 3, white: 4 },
      prestigePoints: 1,
      crowns: 0,
      ability: "steal",
      level: 2,
      index: "2b1",
    },
    {
      color: "black",
      cost: { blue: 2, white: 5 },
      prestigePoints: 1,
      crowns: 0,
      bonus: true,
      level: 2,
      index: "2b2",
    },
    {
      color: "black",
      cost: { pearl: 1, red: 2, green: 2, blue: 2 },
      prestigePoints: 2,
      crowns: 1,
      level: 2,
      index: "2b3",
    },
    {
      color: "black",
      cost: { pearl: 1, black: 4, red: 2 },
      prestigePoints: 2,
      crowns: 0,
      ability: "privilege",
      level: 2,
      index: "2b4",
    },
    // Blue
    {
      color: "blue",
      cost: { black: 3, green: 4 },
      prestigePoints: 1,
      crowns: 0,
      ability: "steal",
      level: 2,
      index: "2l1",
    },
    {
      color: "blue",
      cost: { red: 2, green: 5 },
      prestigePoints: 1,
      crowns: 0,
      bonus: true,
      level: 2,
      index: "2l2",
    },
    {
      color: "blue",
      cost: { pearl: 1, black: 2, red: 2, white: 2 },
      prestigePoints: 2,
      crowns: 1,
      level: 2,
      index: "2l3",
    },
    {
      color: "blue",
      cost: { pearl: 1, blue: 4, white: 2 },
      prestigePoints: 2,
      crowns: 0,
      ability: "privilege",
      level: 2,
      index: "2l4",
    },
    // Green
    {
      color: "green",
      cost: { red: 4, white: 3 },
      prestigePoints: 1,
      crowns: 0,
      ability: "steal",
      level: 2,
      index: "2g1",
    },
    {
      color: "green",
      cost: { black: 2, red: 5 },
      prestigePoints: 1,
      crowns: 0,
      bonus: true,
      level: 2,
      index: "2g2",
    },
    {
      color: "green",
      cost: { pearl: 1, black: 2, blue: 2, white: 2 },
      prestigePoints: 2,
      crowns: 1,
      level: 2,
      index: "2g3",
    },
    {
      color: "green",
      cost: { pearl: 1, green: 4, blue: 2 },
      prestigePoints: 2,
      crowns: 0,
      ability: "privilege",
      level: 2,
      index: "2g4",
    },
    // Red
    {
      color: "red",
      cost: { black: 4, blue: 3 },
      prestigePoints: 1,
      crowns: 0,
      ability: "steal",
      level: 2,
      index: "2r1",
    },
    {
      color: "red",
      cost: { black: 5, white: 2 },
      prestigePoints: 1,
      crowns: 0,
      bonus: true,
      level: 2,
      index: "2r2",
    },
    {
      color: "red",
      cost: { pearl: 1, green: 2, blue: 2, white: 2 },
      prestigePoints: 1,
      crowns: 1,
      level: 2,
      index: "2r3",
    },
    {
      color: "red",
      cost: { pearl: 1, red: 4, green: 2 },
      prestigePoints: 2,
      crowns: 0,
      ability: "privilege",
      level: 2,
      index: "2r4",
    },

    // White
    {
      color: "white",
      cost: { red: 3, blue: 4 },
      prestigePoints: 1,
      crowns: 0,
      ability: "steal",
      level: 2,
      index: "2w1",
    },
    {
      color: "white",
      cost: { green: 2, blue: 5 },
      prestigePoints: 1,
      crowns: 0,
      bonus: true,
      level: 2,
      index: "2w2",
    },
    {
      color: "white",
      cost: { pearl: 1, black: 2, red: 2, green: 2 },
      prestigePoints: 2,
      crowns: 0,
      level: 2,
      index: "2w3",
    },
    {
      color: "white",
      cost: { pearl: 1, black: 2, white: 4 },
      prestigePoints: 2,
      crowns: 0,
      ability: "privilege",
      level: 2,
      index: "2w4",
    },
    {
      color: "points",
      cost: { pearl: 1, blue: 6 },
      prestigePoints: 5,
      crowns: 0,
      level: 2,
      index: "2p",
    },
    {
      color: "joker",
      cost: { pearl: 1, green: 6 },
      prestigePoints: 2,
      crowns: 0,
      level: 2,
      index: "2j1",
    },
    {
      color: "joker",
      cost: { pearl: 1, green: 6 },
      prestigePoints: 0,
      crowns: 2,
      level: 2,
      index: "2j2",
    },
    {
      color: "joker",
      cost: { pearl: 1, blue: 6 },
      prestigePoints: 0,
      crowns: 2,
      level: 2,
      index: "2j3",
    },
  ],
  ["LEVEL_THREE"]: [
    // Black
    {
      color: "black",
      cost: { pearl: 1, red: 3, green: 5, white: 3 },
      prestigePoints: 3,
      crowns: 2,
      level: 3,
      index: "3b1",
    },
    {
      color: "black",
      cost: { black: 6, red: 2, white: 2 },
      prestigePoints: 4,
      crowns: 0,
      level: 3,
      index: "3b2",
    },
    // Blue
    {
      color: "blue",
      cost: { pearl: 1, black: 5, green: 3, white: 3 },
      prestigePoints: 3,
      crowns: 2,
      level: 3,
      index: "3l1",
    },
    {
      color: "blue",
      cost: { green: 2, blue: 6, white: 2 },
      prestigePoints: 4,
      crowns: 0,
      level: 3,
      index: "3l2",
    },
    // Green
    {
      color: "green",
      cost: { pearl: 1, red: 3, blue: 3, white: 5 },
      prestigePoints: 3,
      crowns: 2,
      level: 3,
      index: "3g1",
    },
    {
      color: "green",
      cost: { red: 2, green: 6, blue: 2 },
      prestigePoints: 4,
      crowns: 0,
      level: 3,
      index: "3g2",
    },
    // Red
    {
      color: "red",
      cost: { pearl: 1, black: 3, green: 3, blue: 5 },
      prestigePoints: 3,
      crowns: 2,
      level: 3,
      index: "3r1",
    },
    {
      color: "red",
      cost: { black: 2, red: 6, green: 2 },
      prestigePoints: 4,
      crowns: 0,
      level: 3,
      index: "3r2",
    },
    // White
    {
      color: "white",
      cost: { pearl: 1, black: 3, red: 5, blue: 3 },
      prestigePoints: 3,
      crowns: 2,
      level: 3,
      index: "3w1",
    },
    {
      color: "white",
      cost: { black: 2, blue: 2, white: 6 },
      prestigePoints: 4,
      crowns: 0,
      level: 3,
      index: "3w2",
    },
    {
      color: "points",
      cost: { white: 8 },
      prestigePoints: 6,
      crowns: 0,
      level: 3,
      index: "3p",
    },
    {
      color: "joker",
      cost: { black: 8 },
      prestigePoints: 0,
      crowns: 3,
      level: 3,
      index: "3j1",
    },
    {
      color: "joker",
      cost: { red: 8 },
      prestigePoints: 3,
      crowns: 0,
      ability: "turn",
      level: 3,
      index: "3j2",
    },
  ],
};

const NOBLE_TILES = [
  {
    prestigePoints: 2,
    ability: "steal",
    index: "1",
  },
  {
    prestigePoints: 2,
    ability: "turn",
    index: "2",
  },
  {
    prestigePoints: 2,
    ability: "privilege",
    index: "3",
  },
  {
    prestigePoints: 3,
    index: "4",
  },
];

module.exports = {
  DEV_CARDS,
  NOBLE_TILES,
};
